version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mynetwork
    ports:
      - "27017:27017"
    logging:
      driver: "none"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/myDB
    networks:
      - mynetwork
    dns:
      - 1.1.1.1

networks:
  mynetwork:
    driver: bridge
